/***************************************************************************
 *  Original Diku Mud copyright (C) 1990, 1991 by Sebastian Hammer,        *
 *  Michael Seifert, Hans Henrik St{rfeldt, Tom Madsen, and Katja Nyboe.   *
 *                                                                         *
 *  Merc Diku Mud improvments copyright (C) 1992, 1993 by Michael          *
 *  Chastain, Michael Quan, and Mitchell Tse.                              *
 *                                                                         *
 *  In order to use any part of this Merc Diku Mud, you must comply with   *
 *  both the original Diku license in 'license.doc' as well the Merc       *
 *  license in 'license.txt'.  In particular, you may not remove either of *
 *  these copyright notices.                                               *
 *                                                                         *
 *  Much time and thought has gone into this software and you are          *
 *  benefitting.  We hope that you share your changes too.  What goes      *
 *  around, comes around.                                                  *
 ***************************************************************************/

/***************************************************************************
*	ROM 2.4 is copyright 1993-1995 Russ Taylor			   *
*	ROM has been brought to you by the ROM consortium		   *
*	    Russ Taylor (rtaylor@pacinfo.com)				   *
*	    Gabrielle Taylor (gtaylor@pacinfo.com)			   *
*	    Brian Moore (rom@rom.efn.org)				   *
*	By using this code, you have agreed to follow the terms of the	   *
*	ROM license, in the file Rom24/doc/rom.license			   *
***************************************************************************/

/*************************************************************************** 
*       ROT 1.4 is copyright 1996-1997 by Russ Walsh                       * 
*       By using this code, you have agreed to follow the terms of the     * 
*       ROT license, in the file doc/rot.license                           * 
***************************************************************************/
/*
 * Copyright (C) 2007-2011 See the AUTHORS.BlinkenMUD file for details
 * By using this code, you have agreed to follow the terms of the   
 * ROT license, in the file doc/rot.license        
*/

#include <sys/types.h>
#include <stdio.h>
#include <time.h>
#include "merc.h"
#include "magic.h"
#include "interp.h"


char *const dir_name[] = {
  "north", "east", "south", "west", "up", "down",
  "north", "east", "south", "west", "up", "down"
};

const sh_int rev_dir[] = {
  2, 3, 0, 1, 5, 4, 2, 3, 0, 1, 5, 4
};

const sh_int movement_loss[SECT_MAX] = {
  1, 2, 2, 3, 4, 6, 4, 1, 6, 10, 6
};

/* item type list */
const struct item_type item_table[] = {
  {ITEM_LIGHT, "light"},
  {ITEM_SCROLL, "scroll"},
  {ITEM_WAND, "wand"},
  {ITEM_STAFF, "staff"},
  {ITEM_WEAPON, "weapon"},
  {ITEM_TREASURE, "treasure"},
  {ITEM_ARMOR, "armor"},
  {ITEM_POTION, "potion"},
  {ITEM_CLOTHING, "clothing"},
  {ITEM_FURNITURE, "furniture"},
  {ITEM_TRASH, "trash"},
  {ITEM_CONTAINER, "container"},
  {ITEM_DRINK_CON, "drink"},
  {ITEM_KEY, "key"},
  {ITEM_FOOD, "food"},
  {ITEM_MONEY, "money"},
  {ITEM_BOAT, "boat"},
  {ITEM_CORPSE_NPC, "npc_corpse"},
  {ITEM_CORPSE_PC, "pc_corpse"},
  {ITEM_FOUNTAIN, "fountain"},
  {ITEM_PILL, "pill"},
  {ITEM_PROTECT, "protect"},
  {ITEM_MAP, "map"},
  {ITEM_PORTAL, "portal"},
  {ITEM_WARP_STONE, "warp_stone"},
  {ITEM_ROOM_KEY, "room_key"},
  {ITEM_GEM, "gem"},
  {ITEM_JEWELRY, "jewelry"},
  {ITEM_JUKEBOX, "jukebox"},
  {ITEM_DEMON_STONE, "demon_stone"},
  {ITEM_EXIT, "exit"},
  {ITEM_PIT, "pit"},
  {ITEM_THROWING, "throwing"},
  {0, NULL}
};


/* weapon selection table */
const struct weapon_type weapon_table[] = {
  {"sword", OBJ_VNUM_SCHOOL_SWORD, WEAPON_SWORD, &gsn_sword},
  {"mace", OBJ_VNUM_SCHOOL_MACE, WEAPON_MACE, &gsn_mace},
  {"dagger", OBJ_VNUM_SCHOOL_DAGGER, WEAPON_DAGGER, &gsn_dagger},
  {"axe", OBJ_VNUM_SCHOOL_AXE, WEAPON_AXE, &gsn_axe},
  {"staff", OBJ_VNUM_SCHOOL_STAFF, WEAPON_SPEAR, &gsn_spear},
  {"flail", OBJ_VNUM_SCHOOL_FLAIL, WEAPON_FLAIL, &gsn_flail},
  {"whip", OBJ_VNUM_SCHOOL_WHIP, WEAPON_WHIP, &gsn_whip},
  {"polearm", OBJ_VNUM_SCHOOL_POLEARM, WEAPON_POLEARM, &gsn_polearm},
  {NULL, 0, 0, NULL}
};



/* wiznet table and prototype for future flag setting */
const struct wiznet_type wiznet_table[] = {
  {"on", WIZ_ON, 0},
  {"prefix", WIZ_PREFIX, 0},
  {"ticks", WIZ_TICKS, IM},
  {"logins", WIZ_LOGINS, IM},
  {"sites", WIZ_SITES, IM},
  {"links", WIZ_LINKS, L7},
  {"newbies", WIZ_NEWBIE, 0},
  {"spam", WIZ_SPAM, L5},
  {"deaths", WIZ_DEATHS, IM},
  {"resets", WIZ_RESETS, L4},
  {"mobdeaths", WIZ_MOBDEATHS, L4},
  {"flags", WIZ_FLAGS, L5},
  {"penalties", WIZ_PENALTIES, L5},
  {"saccing", WIZ_SACCING, L5},
  {"levels", WIZ_LEVELS, 0},
  {"load", WIZ_LOAD, L2},
  {"restore", WIZ_RESTORE, L2},
  {"snoops", WIZ_SNOOPS, L2},
  {"switches", WIZ_SWITCHES, L2},
  {"secure", WIZ_SECURE, L1},
  {NULL, 0, 0}
};

/* attack table  -- not very organized :(
 * Be sure to keep MAX_DAMAGE_MESSAGE up
 * to date in merc.h
 */
const struct attack_type attack_table[] = {
  {"none", "hit", -1},		/*  0 */
  {"slice", "slice", DAM_SLASH},
  {"stab", "stab", DAM_PIERCE},
  {"slash", "slash", DAM_SLASH},
  {"whip", "whip", DAM_SLASH},
  {"claw", "claw", DAM_SLASH},	/*  5 */
  {"blast", "blast", DAM_BASH},
  {"pound", "pound", DAM_BASH},
  {"crush", "crush", DAM_BASH},
  {"grep", "grep", DAM_SLASH},
  {"bite", "bite", DAM_PIERCE},	/* 10 */
  {"pierce", "pierce", DAM_PIERCE},
  {"suction", "suction", DAM_BASH},
  {"beating", "beating", DAM_BASH},
  {"digestion", "digestion", DAM_ACID},
  {"charge", "charge", DAM_BASH},	/* 15 */
  {"slap", "slap", DAM_BASH},
  {"punch", "punch", DAM_BASH},
  {"wrath", "wrath", DAM_ENERGY},
  {"magic", "magic", DAM_ENERGY},
  {"divine", "divine power", DAM_HOLY},	/* 20 */
  {"cleave", "cleave", DAM_SLASH},
  {"scratch", "scratch", DAM_PIERCE},
  {"peck", "peck", DAM_PIERCE},
  {"peckb", "peck", DAM_BASH},
  {"chop", "chop", DAM_SLASH},	/* 25 */
  {"sting", "sting", DAM_PIERCE},
  {"smash", "smash", DAM_BASH},
  {"shbite", "shocking bite", DAM_LIGHTNING},
  {"flbite", "flaming bite", DAM_FIRE},
  {"frbite", "freezing bite", DAM_COLD},	/* 30 */
  {"acbite", "acidic bite", DAM_ACID},
  {"chomp", "chomp", DAM_PIERCE},
  {"drain", "life drain", DAM_NEGATIVE},
  {"thrust", "thrust", DAM_PIERCE},
  {"slime", "slime", DAM_ACID},
  {"shock", "shock", DAM_LIGHTNING},
  {"thwack", "thwack", DAM_BASH},
  {"flame", "flame", DAM_FIRE},
  {"chill", "chill", DAM_COLD},
  {"typo", "typo", DAM_SLASH},	/* 40 */
  {NULL, NULL, 0}
};

/* race table */
const struct race_type race_table[] = {
/*
    {
	name,		pc_race?,
	act bits,
	aff_by bits,
	off bits,
	imm,
	res,
	vuln,
	shd bits,
	form,		parts,	remort_race 
    },
*/
  {
    "unique",
    FALSE,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  },

  {
   "human", TRUE,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, FALSE},

  {
   "elf",
   TRUE,
   0,
   AFF_INFRARED,
   0,
   0,
   RES_CHARM,
   VULN_IRON,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K,
   FALSE
  },

  {
   "dwarf", TRUE,
   0,
   AFF_INFRARED,
   0,
   0,
   RES_POISON | RES_DISEASE,
   VULN_DROWNING,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, FALSE},

  {
   "giant", TRUE,
   0,
   0,
   0,
   0,
   RES_FIRE | RES_COLD,
   VULN_MENTAL | VULN_LIGHTNING,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, FALSE},

  {
   "pixie", TRUE,
   0,
   AFF_FLYING | AFF_DETECT_MAGIC | AFF_INFRARED,
   0,
   0,
   RES_CHARM | RES_MENTAL,
   VULN_IRON,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K | P, FALSE},

  {
   "halfling", TRUE,
   0,
   AFF_PASS_DOOR,
   0,
   0,
   RES_POISON | RES_DISEASE,
   VULN_LIGHT,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, FALSE},

  {
   "halforc", TRUE,
   0,
   AFF_BERSERK,
   0,
   0,
   RES_MAGIC | RES_WEAPON,
   VULN_MENTAL,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, FALSE},

  {
   "goblin", TRUE,
   0,
   AFF_INFRARED,
   0,
   0,
   RES_MENTAL,
   VULN_SILVER | VULN_LIGHT | VULN_WOOD | VULN_HOLY,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, FALSE},

  {
   "halfelf", TRUE,
   0,
   AFF_FARSIGHT,
   0,
   0,
   0,
   0,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, FALSE},

  {
   "avian", TRUE,
   0,
   AFF_FLYING | AFF_DETECT_INVIS | AFF_DETECT_HIDDEN | AFF_FARSIGHT |
   AFF_INFRARED,
   0,
   0,
   RES_LIGHTNING,
   VULN_DISEASE | VULN_POISON,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K | P, TRUE},

  {
   "gnome", TRUE,
   0,
   AFF_INFRARED,
   0,
   0,
   RES_MENTAL,
   VULN_DROWNING,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, FALSE},

  {
   "draconian", TRUE,
   0,
   AFF_FLYING,
   0,
   IMM_POISON | IMM_DISEASE,
   RES_FIRE | RES_COLD,
   VULN_SLASH | VULN_PIERCE | VULN_LIGHTNING,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K | P | Q, TRUE},

  {
   "centaur", TRUE,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, TRUE},

  {
   "gnoll", TRUE,
   0,
   AFF_DETECT_HIDDEN | AFF_DARK_VISION,
   0,
   0,
   0,
   VULN_SILVER,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K | U | V, FALSE},

  {
   "heucuva", TRUE,
   0,
   AFF_DARK_VISION,
   0,
   IMM_NEGATIVE | IMM_POISON | IMM_DISEASE,
   RES_WEAPON,
   VULN_HOLY | VULN_LIGHT | VULN_SILVER,
   0,
   A | H | M | V, A | B | C | G | H | I | J | K, TRUE},

  {
   "kenku", TRUE,
   0,
   AFF_FARSIGHT | AFF_DETECT_HIDDEN | AFF_INFRARED | AFF_FLYING,
   0,
   0,
   RES_COLD,
   0,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K | P, TRUE},

  {
   "minotaur", TRUE,
   0,
   AFF_FARSIGHT,
   0,
   IMM_POISON,
   0,
   VULN_BASH,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K | W, TRUE},

  {
   "satyr", TRUE,
   0,
   AFF_DETECT_HIDDEN | AFF_DETECT_EVIL | AFF_DETECT_GOOD,
   0,
   IMM_FIRE,
   RES_NEGATIVE,
   VULN_HOLY | VULN_LIGHT,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, TRUE},

  {
   "titan", TRUE,
   0,
   AFF_DETECT_INVIS | AFF_BERSERK,
   0,
   IMM_CHARM,
   RES_WEAPON,
   0,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, TRUE},

  {
   "bat", FALSE,
   0,
   AFF_FLYING | AFF_DARK_VISION,
   OFF_DODGE | OFF_FAST,
   0,
   0,
   VULN_LIGHT,
   0,
   A | G | V, A | C | D | E | F | H | J | K | P, FALSE},

  {
   "bear", FALSE,
   0,
   0,
   OFF_CRUSH | OFF_DISARM | OFF_BERSERK,
   0,
   RES_BASH | RES_COLD,
   0,
   0,
   A | G | V, A | B | C | D | E | F | H | J | K | U | V, FALSE},

  {
   "cat", FALSE,
   0,
   AFF_DARK_VISION,
   OFF_FAST | OFF_DODGE,
   0,
   0,
   0,
   0,
   A | G | V, A | C | D | E | F | H | J | K | Q | U | V, FALSE},

  {
   "centipede", FALSE,
   0,
   AFF_DARK_VISION,
   0,
   0,
   RES_PIERCE | RES_COLD,
   VULN_BASH,
   0,
   A | B | G | O, A | C | K, FALSE},

  {
   "dog", FALSE,
   0,
   0,
   OFF_FAST,
   0,
   0,
   0,
   0,
   A | G | V, A | C | D | E | F | H | J | K | U | V, FALSE},

  {
   "doll", FALSE,
   0,
   0,
   0,
   IMM_COLD | IMM_POISON | IMM_HOLY | IMM_NEGATIVE | IMM_MENTAL | IMM_DISEASE
   | IMM_DROWNING,
   RES_BASH | RES_LIGHT,
   VULN_SLASH | VULN_FIRE | VULN_ACID | VULN_LIGHTNING | VULN_ENERGY,
   0,
   E | J | M | cc, A | B | C | G | H | K, FALSE},

  {"dragon", FALSE,
   0,
   AFF_INFRARED | AFF_FLYING,
   0,
   0,
   RES_FIRE | RES_BASH | RES_CHARM,
   VULN_PIERCE | VULN_COLD,
   0,
   A | H | Z, A | C | D | E | F | G | H | I | J | K | P | Q | U | V | X,
   FALSE},

  {
   "fido", FALSE,
   0,
   0,
   OFF_DODGE | ASSIST_RACE,
   0,
   0,
   VULN_MAGIC,
   0,
   A | B | G | V, A | C | D | E | F | H | J | K | Q | V, FALSE},

  {
   "fox", FALSE,
   0,
   AFF_DARK_VISION,
   OFF_FAST | OFF_DODGE,
   0,
   0,
   0,
   0,
   A | G | V, A | C | D | E | F | H | J | K | Q | V, FALSE},

  {
   "hobgoblin", FALSE,
   0,
   AFF_INFRARED,
   0,
   0,
   RES_DISEASE | RES_POISON,
   0,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K | Y, FALSE},

  {
   "kobold", FALSE,
   0,
   AFF_INFRARED,
   0,
   0,
   RES_POISON,
   VULN_MAGIC,
   0,
   A | B | H | M | V, A | B | C | D | E | F | G | H | I | J | K | Q, FALSE},

  {
   "lizard", FALSE,
   0,
   0,
   0,
   0,
   RES_POISON,
   VULN_COLD,
   0,
   A | G | X | cc, A | C | D | E | F | H | K | Q | V, FALSE},

  {
   "modron", FALSE,
   0,
   AFF_INFRARED,
   ASSIST_RACE | ASSIST_ALIGN,
   IMM_CHARM | IMM_DISEASE | IMM_MENTAL | IMM_HOLY | IMM_NEGATIVE,
   RES_FIRE | RES_COLD | RES_ACID,
   0,
   0,
   H, A | B | C | G | H | J | K, FALSE},

  {
   "orc", FALSE,
   0,
   AFF_INFRARED,
   0,
   0,
   RES_DISEASE,
   VULN_LIGHT,
   0,
   A | H | M | V, A | B | C | D | E | F | G | H | I | J | K, FALSE},

  {
   "pig", FALSE,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   A | G | V, A | C | D | E | F | H | J | K, FALSE},

  {
   "rabbit", FALSE,
   0,
   0,
   OFF_DODGE | OFF_FAST,
   0,
   0,
   0,
   0,
   A | G | V, A | C | D | E | F | H | J | K, FALSE},

  {
   "school monster", FALSE,
   ACT_NOALIGN,
   0,
   0,
   IMM_CHARM | IMM_SUMMON,
   0,
   VULN_MAGIC,
   0,
   A | M | V, A | B | C | D | E | F | H | J | K | Q | U, FALSE},

  {
   "snake", FALSE,
   0,
   0,
   0,
   0,
   RES_POISON,
   VULN_COLD,
   0,
   A | G | X | Y | cc, A | D | E | F | K | L | Q | V | X, FALSE},

  {
   "song bird", FALSE,
   0,
   AFF_FLYING,
   OFF_FAST | OFF_DODGE,
   0,
   0,
   0,
   0,
   A | G | W, A | C | D | E | F | H | K | P, FALSE},

  {
   "troll", FALSE,
   0,
   AFF_REGENERATION | AFF_INFRARED | AFF_DETECT_HIDDEN,
   OFF_BERSERK,
   0,
   RES_CHARM | RES_BASH,
   VULN_FIRE | VULN_ACID,
   0,
   A | B | H | M | V, A | B | C | D | E | F | G | H | I | J | K | U | V,
   FALSE},

  {
   "water fowl", FALSE,
   0,
   AFF_SWIM | AFF_FLYING,
   0,
   0,
   RES_DROWNING,
   0,
   0,
   A | G | W, A | C | D | E | F | H | K | P, FALSE},

  {
   "wolf", FALSE,
   0,
   AFF_DARK_VISION,
   OFF_FAST | OFF_DODGE,
   0,
   0,
   0,
   0,
   A | G | V, A | C | D | E | F | J | K | Q | V, FALSE},

  {
   "wyvern", FALSE,
   0,
   AFF_FLYING | AFF_DETECT_INVIS | AFF_DETECT_HIDDEN,
   OFF_BASH | OFF_FAST | OFF_DODGE,
   IMM_POISON,
   0,
   VULN_LIGHT,
   0,
   A | B | G | Z, A | C | D | E | F | H | J | K | Q | V | X, FALSE},

  {"unique", FALSE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},

  {
    NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,FALSE}
};

const struct pc_race_type pc_race_table[] = {
  {
   "null race", "",
   0,
   {100, 100, 100, 100, 100, 100, 100,
    100, 100, 100, 100, 100, 100, 100},
   {""},
   {13, 13, 13, 13, 13},
   {18, 18, 18, 18, 18},
   0},

/*
    {
	"race name", 	short name,
	points,
	{ class multipliers },
	{ bonus skills },
	{ base stats },
	{ max stats },
	size 
    },
*/
  {
   "human", "Human",
   0,
   {100, 100, 100, 100, 100, 100, 100,
    90, 90, 90, 90, 90, 90, 90},
   {""},
   {13, 13, 13, 13, 13},
   {18, 18, 18, 18, 18},
   SIZE_MEDIUM},

  {
   "elf", "Elf",
   5,
   {100, 125, 100, 120, 120, 105, 115,
    90, 113, 90, 108, 95, 95, 104},
   {"sneak", "hide"},
   {12, 14, 13, 15, 11},
   {16, 20, 18, 21, 15},
   SIZE_SMALL},

  {
   "dwarf", "Dwarf",
   8,
   {150, 100, 125, 100, 110, 110, 110,
    135, 90, 113, 90, 113, 99, 99},
   {"berserk"},
   {14, 12, 13, 11, 15},
   {20, 16, 19, 15, 21},
   SIZE_MEDIUM},

  {
   "giant", "Giant",
   6,
   {200, 125, 150, 105, 125, 150, 120,
    180, 113, 135, 95, 135, 135, 108},
   {"bash", "fast healing"},
   {16, 11, 13, 11, 14},
   {22, 15, 18, 15, 20},
   SIZE_LARGE},

  {
   "pixie", "Pixie",
   6,
   {100, 100, 120, 200, 150, 100, 150,
    90, 90, 108, 180, 95, 90, 135},
   {""},
   {10, 15, 15, 15, 10},
   {14, 21, 21, 20, 14},
   SIZE_TINY},

  {
   "halfling", "Hfling",
   5,
   {105, 120, 100, 150, 150, 120, 120,
    95, 108, 90, 135, 108, 108, 108},
   {"sneak", "hide"},
   {11, 14, 12, 15, 13},
   {15, 20, 16, 21, 18},
   SIZE_SMALL},

  {
   "halforc", "Hf-Orc",
   6,
   {200, 200, 120, 100, 125, 150, 105,
    180, 180, 108, 90, 135, 135, 95},
   {"fast healing"},
   {14, 11, 11, 14, 15},
   {19, 15, 15, 20, 21},
   SIZE_MEDIUM},

  {
   "goblin", "Goblin",
   5,
   {105, 125, 110, 125, 120, 120, 110,
    95, 113, 99, 113, 99, 108, 99},
   {"sneak", "hide"},
   {11, 14, 12, 15, 14},
   {16, 20, 16, 19, 20},
   SIZE_SMALL},

  {
   "halfelf", "Hf-Elf",
   2,
   {105, 105, 105, 105, 105, 105, 105,
    95, 95, 95, 95, 95, 95, 95},
   {""},
   {12, 13, 14, 13, 13},
   {17, 18, 19, 18, 18},
   SIZE_MEDIUM},

  {
   "avian", "Avian",
   5,
   {110, 105, 150, 125, 120, 100, 120,
    99, 95, 135, 113, 108, 90, 108},
   {""},
   {12, 14, 15, 11, 12},
   {17, 19, 20, 16, 17},
   SIZE_LARGE},

  {
   "gnome", "Gnome",
   4,
   {100, 110, 150, 150, 125, 105, 150,
    90, 99, 135, 135, 99, 95, 135},
   {""},
   {11, 15, 14, 12, 12},
   {16, 20, 19, 15, 15},
   SIZE_SMALL},

  {
   "draconian", "Dracon",
   11,
   {125, 150, 200, 100, 110, 125, 150,
    113, 135, 180, 90, 108, 113, 135},
   {"fast healing"},
   {16, 13, 12, 11, 15},
   {22, 18, 16, 15, 21},
   SIZE_HUGE},

  {
   "centaur", "Centr",
   9,
   {100, 110, 100, 175, 110, 110, 95,
    90, 100, 90, 165, 100, 100, 85},
   {"enhanced damage"},
   {15, 12, 10, 8, 16},
   {20, 17, 15, 13, 21},
   SIZE_LARGE},

  {
   "gnoll", "Gnoll",
   7,
   {110, 110, 125, 110, 175, 110, 110,
    100, 100, 115, 100, 165, 100, 100},
   {""},
   {15, 11, 10, 16, 15},
   {20, 16, 15, 20, 19},
   SIZE_LARGE},

  {
   "heucuva", "Heucuv",
   10,
   {110, 110, 110, 100, 110, 110, 100,
    100, 100, 100, 90, 100, 100, 90},
   {"second attack"},
   {20, 5, 5, 20, 20},
   {25, 10, 10, 25, 25},
   SIZE_MEDIUM},

  {
   "kenku", "Kenku",
   5,
   {125, 110, 150, 150, 110, 125, 180,
    115, 100, 140, 140, 100, 115, 170},
   {"meditation"},
   {14, 14, 16, 15, 14},
   {19, 19, 21, 20, 19},
   SIZE_MEDIUM},

  {
   "minotaur", "Minotr",
   7,
   {110, 110, 110, 95, 110, 110, 110,
    100, 100, 100, 85, 100, 100, 100},
   {"enhanced damage"},
   {18, 11, 10, 11, 17},
   {23, 16, 15, 16, 22},
   SIZE_LARGE},

  {
   "satyr", "Satyr",
   6,
   {110, 110, 110, 175, 110, 110, 150,
    100, 100, 100, 165, 100, 100, 140},
   {""},
   {18, 14, 5, 9, 16},
   {23, 19, 10, 14, 21},
   SIZE_LARGE},

  {
   "titan", "Titan",
   11,
   {180, 105, 130, 105, 105, 130, 100,
    170, 93, 115, 95, 95, 115, 98},
   {"fast healing"},
   {20, 13, 13, 10, 20},
   {25, 18, 18, 15, 25},
   SIZE_GIANT}
};




/*
 * Class table.
 */
const struct class_type class_table[MAX_CLASS] = {

/*
    {
	name, who, attr_prime, weapon,
	{guild1, guild2, guild3}, thac0_00, thac0_32, hp_min, hp_max, mana?,
	base_group, default_group, remort_class
    }
*/

  {
   "mage", "Mag", STAT_INT, OBJ_VNUM_SCHOOL_DAGGER,
   {3018, 9618, 18113}, 75, 20, 6, 6, 8, TRUE,
   "mage basics", "mage default", FALSE},

  {
   "cleric", "Cle", STAT_WIS, OBJ_VNUM_SCHOOL_MACE,
   {3003, 9619, 5699}, 75, 20, 2, 7, 10, TRUE,
   "cleric basics", "cleric default", FALSE},

  {
   "thief", "Thi", STAT_DEX, OBJ_VNUM_SCHOOL_DAGGER,
   {3028, 9639, 5633}, 75, 20, -4, 8, 13, FALSE,
   "thief basics", "thief default", FALSE},

  {
   "warrior", "War", STAT_STR, OBJ_VNUM_SCHOOL_SWORD,
   {3022, 9633, 5613}, 75, 20, -10, 13, 18, FALSE,
   "warrior basics", "warrior default", FALSE},

  {
   "ranger", "Ran", STAT_STR, OBJ_VNUM_SCHOOL_SPEAR,
   {3372, 9752, 18111}, 75, 20, -4, 9, 13, TRUE,
   "ranger basics", "ranger default", FALSE},

  {
   "druid", "Dru", STAT_WIS, OBJ_VNUM_SCHOOL_POLEARM,
   {3369, 9755, 18111}, 75, 20, 0, 7, 10, TRUE,
   "druid basics", "druid default", FALSE},

  {
   "vampire", "Vam", STAT_CON, OBJ_VNUM_SCHOOL_DAGGER,
   {3375, 9758, 18113}, 75, 20, -30, 6, 8, TRUE,
   "vampire basics", "vampire default", FALSE},

  {
   "wizard", "Wiz", STAT_INT, OBJ_VNUM_SCHOOL_DAGGER,
   {3018, 9618, 18113}, 75, 10, -4, 6, 18, TRUE,
   "wizard basics", "wizard default", TRUE},

  {
   "priest", "Prs", STAT_WIS, OBJ_VNUM_SCHOOL_MACE,
   {3003, 9619, 5699}, 75, 10, 2, -3, 20, TRUE,
   "priest basics", "priest default", TRUE},

  {
   "mercenary", "Mer", STAT_DEX, OBJ_VNUM_SCHOOL_DAGGER,
   {3028, 9639, 5633}, 75, 10, -14, 8, 23, FALSE,
   "mercenary basics", "mercenary default", TRUE},

  {
   "gladiator", "Gla", STAT_STR, OBJ_VNUM_SCHOOL_SWORD,
   {3022, 9633, 5613}, 75, 10, -20, 14, 25, FALSE,
   "gladiator basics", "gladiator default", TRUE},

  {
   "strider", "Str", STAT_INT, OBJ_VNUM_SCHOOL_DAGGER,
   {3372, 9752, 18111}, 75, 10, -14, 10, 25, TRUE,
   "strider basics", "strider default", TRUE},

  {
   "sage", "Sag", STAT_WIS, OBJ_VNUM_SCHOOL_POLEARM,
   {3369, 9755, 18111}, 75, 10, -10, 7, 20, TRUE,
   "sage basics", "sage default", TRUE},

  {
   "lich", "Lic", STAT_CON, OBJ_VNUM_SCHOOL_DAGGER,
   {3375, 9758, 18113}, 75, 10, -40, 6, 18, TRUE,
   "lich basics", "lich default", TRUE}
};


/*
 * Titles.
 */
char *const title_table[MAX_CLASS][MAX_LEVEL + 1][2] = {

/*	Mage	*/

  {
   {"Man", "Woman"},

   {"Novice of Magic", "Novice of Magic"},
   {"Apprentice of Magic", "Apprentice of Magic"},
   {"Spell Novice", "Spell Novice"},
   {"Spell Student", "Spell Student"},
   {"Scholar of Magic", "Scholar of Magic"},
   {"Scholar of Wizardry", "Scholar of Wizardry"},
   {"Delver in Scrolls", "Delveress in Scrolls"},
   {"Delver in Spells", "Delveress in Spells"},
   {"Medium of Magic", "Medium of Magic"},
   {"Medium of Wizardry", "Medium of Wizardry"},
   {"Scribe of Magic", "Scribess of Magic"},
   {"Scribe of Wizardry", "Scribess of Wizardry"},
   {"Minor Seer", "Minor Seeress"},
   {"Seer", "Seeress"},
   {"Minor Sage", "Minor Sage"},
   {"Sage", "Sage"},
   {"Minor Illusionist", "Minor Illusionist"},
   {"Illusionist", "Illusionist"},
   {"Minor Abjurer", "Minor Abjuress"},
   {"Abjurer", "Abjuress"},
   {"Minor Invoker", "Minor Invoker"},
   {"Invoker", "Invoker"},
   {"Minor Enchanter", "Minor Enchantress"},
   {"Enchanter", "Enchantress"},
   {"Minor Conjurer", "Minor Conjuress"},
   {"Conjurer", "Conjuress"},
   {"Minor Magician", "Minor Witch"},
   {"Magician", "Witch"},
   {"Minor Creator", "Minor Creator"},
   {"Creator", "Creator"},
   {"Minor Savant", "Minor Savant"},
   {"Savant", "Savant"},
   {"Minor Magus", "Minor Craftess"},
   {"Magus", "Craftess"},
   {"Minor Wizard", "Minor Wizard"},
   {"Wizard", "Wizard"},
   {"Minor Warlock", "Minor War Witch"},
   {"Warlock", "War Witch"},
   {"Minor Sorcerer", "Minor Sorceress"},
   {"Sorcerer", "Sorceress"},
   {"Elder Sorcerer", "Elder Sorceress"},
   {"Elder Sorcerer", "Elder Sorceress"},
   {"Grand Sorcerer", "Grand Sorceress"},
   {"Grand Sorcerer", "Grand Sorceress"},
   {"Great Sorcerer", "Great Sorceress"},
   {"Great Sorcerer", "Great Sorceress"},
   {"Golem Maker", "Golem Maker"},
   {"Golem Maker", "Golem Maker"},
   {"Greater Golem Maker", "Greater Golem Maker"},
   {"Greater Golem Maker", "Greater Golem Maker"},
   {"Maker of Stones", "Maker of Stones",},
   {"Maker of Stones", "Maker of Stones",},
   {"Maker of Potions", "Maker of Potions",},
   {"Maker of Potions", "Maker of Potions",},
   {"Maker of Scrolls", "Maker of Scrolls",},
   {"Maker of Scrolls", "Maker of Scrolls",},
   {"Maker of Wands", "Maker of Wands",},
   {"Maker of Wands", "Maker of Wands",},
   {"Maker of Staves", "Maker of Staves",},
   {"Maker of Staves", "Maker of Staves",},
   {"Demon Summoner", "Demon Summoner"},
   {"Demon Summoner", "Demon Summoner"},
   {"Greater Demon Summoner", "Greater Demon Summoner"},
   {"Greater Demon Summoner", "Greater Demon Summoner"},
   {"Dragon Charmer", "Dragon Charmer"},
   {"Dragon Charmer", "Dragon Charmer"},
   {"Greater Dragon Charmer", "Greater Dragon Charmer"},
   {"Greater Dragon Charmer", "Greater Dragon Charmer"},
   {"Master of all Magic", "Master of all Magic"},
   {"Master of all Magic", "Master of all Magic"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Master Mage", "Master Mage"},
   {"Mage Hero", "Mage Heroine"},
   {"Squire of Magic", "Squire of Magic"},
   {"Knight of Magic", "Dame of Magic"},
   {"Demigod of Magic", "Demigoddess of Magic"},
   {"Immortal of Magic", "Immortal of Magic"},
   {"God of Magic", "Goddess of Magic"},
   {"Deity of Magic", "Deity of Magic"},
   {"Supremity of Magic", "Supremity of Magic"},
   {"Creator", "Creator"},
   {"Supreme Deity", "Supreme Deity"}
   },

/*	Cleric	*/

  {
   {"Man", "Woman"},

   {"Believer", "Believer"},
   {"Believer", "Believer"},
   {"Attendant", "Attendant"},
   {"Attendant", "Attendant"},
   {"Acolyte", "Acolyte"},
   {"Acolyte", "Acolyte"},
   {"Novice", "Novice"},
   {"Novice", "Novice"},
   {"Missionary", "Missionary"},
   {"Missionary", "Missionary"},
   {"Adept", "Adept"},
   {"Adept", "Adept"},
   {"Deacon", "Deaconess"},
   {"Deacon", "Deaconess"},
   {"Vicar", "Vicaress"},
   {"Vicar", "Vicaress"},
   {"Priest", "Priestess"},
   {"Priest", "Priestess"},
   {"Minister", "Lady Minister"},
   {"Minister", "Lady Minister"},
   {"Canon", "Canon"},
   {"Canon", "Canon"},
   {"Levite", "Levitess"},
   {"Levite", "Levitess"},
   {"Curate", "Curess"},
   {"Curate", "Curess"},
   {"Monk", "Nun"},
   {"Monk", "Nun"},
   {"Healer", "Healess"},
   {"Healer", "Healess"},
   {"Chaplain", "Chaplain"},
   {"Chaplain", "Chaplain"},
   {"Expositor", "Expositress"},
   {"Expositor", "Expositress"},
   {"Bishop", "Bishop"},
   {"Bishop", "Bishop"},
   {"Arch Bishop", "Arch Lady of the Church"},
   {"Arch Bishop", "Arch Lady of the Church"},
   {"Patriarch", "Matriarch"},
   {"Patriarch", "Matriarch"},
   {"Elder Patriarch", "Elder Matriarch"},
   {"Elder Patriarch", "Elder Matriarch"},
   {"Grand Patriarch", "Grand Matriarch"},
   {"Grand Patriarch", "Grand Matriarch"},
   {"Great Patriarch", "Great Matriarch"},
   {"Great Patriarch", "Great Matriarch"},
   {"Demon Killer", "Demon Killer"},
   {"Demon Killer", "Demon Killer"},
   {"Greater Demon Killer", "Greater Demon Killer"},
   {"Greater Demon Killer", "Greater Demon Killer"},
   {"Cardinal of the Sea", "Cardinal of the Sea"},
   {"Cardinal of the Sea", "Cardinal of the Sea"},
   {"Cardinal of the Earth", "Cardinal of the Earth"},
   {"Cardinal of the Earth", "Cardinal of the Earth"},
   {"Cardinal of the Air", "Cardinal of the Air"},
   {"Cardinal of the Air", "Cardinal of the Air"},
   {"Cardinal of the Ether", "Cardinal of the Ether"},
   {"Cardinal of the Ether", "Cardinal of the Ether"},
   {"Cardinal of the Heavens", "Cardinal of the Heavens"},
   {"Cardinal of the Heavens", "Cardinal of the Heavens"},
   {"Avatar of an Immortal", "Avatar of an Immortal"},
   {"Avatar of an Immortal", "Avatar of an Immortal"},
   {"Avatar of a Deity", "Avatar of a Deity"},
   {"Avatar of a Deity", "Avatar of a Deity"},
   {"Avatar of a Supremity", "Avatar of a Supremity"},
   {"Avatar of a Supremity", "Avatar of a Supremity"},
   {"Avatar of an Implementor", "Avatar of an Implementor"},
   {"Avatar of an Implementor", "Avatar of an Implementor"},
   {"Master of all Divinity", "Mistress of all Divinity"},
   {"Master of all Divinity", "Mistress of all Divinity"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Master Cleric", "Master Cleric"},
   {"Holy Hero", "Holy Heroine"},
   {"Holy Squire", "Holy Squire"},
   {"Holy Knight", "Holy Dame"},
   {"Demigod", "Demigoddess",},
   {"Immortal", "Immortal"},
   {"God", "Goddess"},
   {"Deity", "Deity"},
   {"Supreme Master", "Supreme Mistress"},
   {"Creator", "Creator"},
   {"Supreme Deity", "Supreme Deity"}
   },

/*	Thief	*/

  {
   {"Man", "Woman"},

   {"Pilferer", "Pilferess"},
   {"Pilferer", "Pilferess"},
   {"Footpad", "Footpad"},
   {"Footpad", "Footpad"},
   {"Filcher", "Filcheress"},
   {"Filcher", "Filcheress"},
   {"Pick-Pocket", "Pick-Pocket"},
   {"Pick-Pocket", "Pick-Pocket"},
   {"Sneak", "Sneak"},
   {"Sneak", "Sneak"},
   {"Pincher", "Pincheress"},
   {"Pincher", "Pincheress"},
   {"Cut-Purse", "Cut-Purse"},
   {"Cut-Purse", "Cut-Purse"},
   {"Snatcher", "Snatcheress"},
   {"Snatcher", "Snatcheress"},
   {"Sharper", "Sharpress"},
   {"Sharper", "Sharpress"},
   {"Rogue", "Rogue"},
   {"Rogue", "Rogue"},
   {"Robber", "Robber"},
   {"Robber", "Robber"},
   {"Magsman", "Magswoman"},
   {"Magsman", "Magswoman"},
   {"Highwayman", "Highwaywoman"},
   {"Highwayman", "Highwaywoman"},
   {"Burglar", "Burglaress"},
   {"Burglar", "Burglaress"},
   {"Thief", "Thief"},
   {"Thief", "Thief"},
   {"Knifer", "Knifer"},
   {"Knifer", "Knifer"},
   {"Quick-Blade", "Quick-Blade"},
   {"Quick-Blade", "Quick-Blade"},
   {"Killer", "Murderess"},
   {"Killer", "Murderess"},
   {"Brigand", "Brigand"},
   {"Brigand", "Brigand"},
   {"Cut-Throat", "Cut-Throat"},
   {"Cut-Throat", "Cut-Throat"},
   {"Spy", "Spy"},
   {"Spy", "Spy"},
   {"Grand Spy", "Grand Spy"},
   {"Grand Spy", "Grand Spy"},
   {"Master Spy", "Master Spy"},
   {"Master Spy", "Master Spy"},
   {"Assassin", "Assassin"},
   {"Assassin", "Assassin"},
   {"Greater Assassin", "Greater Assassin"},
   {"Greater Assassin", "Greater Assassin"},
   {"Master of Vision", "Mistress of Vision"},
   {"Master of Vision", "Mistress of Vision"},
   {"Master of Hearing", "Mistress of Hearing"},
   {"Master of Hearing", "Mistress of Hearing"},
   {"Master of Smell", "Mistress of Smell"},
   {"Master of Smell", "Mistress of Smell"},
   {"Master of Taste", "Mistress of Taste"},
   {"Master of Taste", "Mistress of Taste"},
   {"Master of Touch", "Mistress of Touch"},
   {"Master of Touch", "Mistress of Touch"},
   {"Crime Lord", "Crime Mistress"},
   {"Crime Lord", "Crime Mistress"},
   {"Infamous Crime Lord", "Infamous Crime Mistress"},
   {"Infamous Crime Lord", "Infamous Crime Mistress"},
   {"Greater Crime Lord", "Greater Crime Mistress"},
   {"Greater Crime Lord", "Greater Crime Mistress"},
   {"Master Crime Lord", "Master Crime Mistress"},
   {"Master Crime Lord", "Master Crime Mistress"},
   {"Godfather", "Godmother"},
   {"Godfather", "Godmother"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Master Thief", "Master Thief"},
   {"Assassin Hero", "Assassin Heroine"},
   {"Squire of Death", "Squire of Death",},
   {"Knight of Death", "Dame of Death"},
   {"Demigod of Assassins", "Demigoddess of Assassins"},
   {"Immortal Assasin", "Immortal Assassin"},
   {"God of Assassins", "God of Assassins",},
   {"Deity of Assassins", "Deity of Assassins"},
   {"Supreme Master", "Supreme Mistress"},
   {"Creator", "Creator"},
   {"Supreme Deity", "Supreme Deity"}
   },

/*	Warrior	*/

  {
   {"Man", "Woman"},

   {"Swordpupil", "Swordpupil"},
   {"Swordpupil", "Swordpupil"},
   {"Recruit", "Recruit"},
   {"Recruit", "Recruit"},
   {"Sentry", "Sentress"},
   {"Sentry", "Sentress"},
   {"Fighter", "Fighter"},
   {"Fighter", "Fighter"},
   {"Soldier", "Soldier"},
   {"Soldier", "Soldier"},
   {"Warrior", "Warrior"},
   {"Warrior", "Warrior"},
   {"Veteran", "Veteran"},
   {"Veteran", "Veteran"},
   {"Swordsman", "Swordswoman"},
   {"Swordsman", "Swordswoman"},
   {"Fencer", "Fenceress"},
   {"Fencer", "Fenceress"},
   {"Combatant", "Combatess"},
   {"Combatant", "Combatess"},
   {"Hero", "Heroine"},
   {"Hero", "Heroine"},
   {"Myrmidon", "Myrmidon"},
   {"Myrmidon", "Myrmidon"},
   {"Swashbuckler", "Swashbuckleress"},
   {"Swashbuckler", "Swashbuckleress"},
   {"Mercenary", "Mercenaress"},
   {"Mercenary", "Mercenaress"},
   {"Swordmaster", "Swordmistress"},
   {"Swordmaster", "Swordmistress"},
   {"Lieutenant", "Lieutenant"},
   {"Lieutenant", "Lieutenant"},
   {"Champion", "Lady Champion"},
   {"Champion", "Lady Champion"},
   {"Dragoon", "Lady Dragoon"},
   {"Dragoon", "Lady Dragoon"},
   {"Cavalier", "Lady Cavalier"},
   {"Cavalier", "Lady Cavalier"},
   {"Knight", "Lady Knight"},
   {"Knight", "Lady Knight"},
   {"Grand Knight", "Grand Knight"},
   {"Grand Knight", "Grand Knight"},
   {"Master Knight", "Master Knight"},
   {"Master Knight", "Master Knight"},
   {"Strider", "Strider"},
   {"Strider", "Strider"},
   {"Grand Strider", "Grand Strider"},
   {"Grand Strider", "Grand Strider"},
   {"Demon Slayer", "Demon Slayer"},
   {"Demon Slayer", "Demon Slayer"},
   {"Greater Demon Slayer", "Greater Demon Slayer"},
   {"Greater Demon Slayer", "Greater Demon Slayer"},
   {"Dragon Slayer", "Dragon Slayer"},
   {"Dragon Slayer", "Dragon Slayer"},
   {"Greater Dragon Slayer", "Greater Dragon Slayer"},
   {"Greater Dragon Slayer", "Greater Dragon Slayer"},
   {"Underlord", "Underlord"},
   {"Underlord", "Underlord"},
   {"Overlord", "Overlord"},
   {"Overlord", "Overlord"},
   {"Baron of Thunder", "Baroness of Thunder"},
   {"Baron of Thunder", "Baroness of Thunder"},
   {"Baron of Storms", "Baroness of Storms"},
   {"Baron of Storms", "Baroness of Storms"},
   {"Baron of Tornadoes", "Baroness of Tornadoes"},
   {"Baron of Tornadoes", "Baroness of Tornadoes"},
   {"Baron of Hurricanes", "Baroness of Hurricanes"},
   {"Baron of Hurricanes", "Baroness of Hurricanes"},
   {"Baron of Meteors", "Baroness of Meteors"},
   {"Baron of Meteors", "Baroness of Meteors"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Master Warrior", "Master Warrior"},
   {"Knight Hero", "Knight Heroine"},
   {"Squire of War", "Squire of War"},
   {"Knight of War", "Dame of War"},
   {"Demigod of War", "Demigoddess of War"},
   {"Immortal Warlord", "Immortal Warlord"},
   {"God of War", "God of War"},
   {"Deity of War", "Deity of War"},
   {"Supreme Master of War", "Supreme Mistress of War"},
   {"Creator", "Creator"},
   {"Supreme Deity", "Supreme Deity"}
   },

/*	Ranger	*/

  {
   {"Man", "Woman"},

   {"Apprentice of the Hunt", "Apprentice of the Hunt"},
   {"Student of the Hunt", "Student of the Hunt"},
   {"Student of the Hunt", "Student of the Hunt"},
   {"Runner", "Runner"},
   {"Runner", "Runner"},
   {"Strider", "Strider"},
   {"Strider", "Strider"},
   {"Scout", "Scout"},
   {"Scout", "Scout"},
   {"Master Scout", "Master Scout"},
   {"Master Scout", "Master Scout"},
   {"Explorer", "Explorer"},
   {"Explorer", "Explorer"},
   {"Tracker", "Tracker"},
   {"Tracker", "Tracker"},
   {"Survivalist", "Survivalist"},
   {"Survivalist", "Survivalist"},
   {"Watcher", "Watcher"},
   {"Watcher", "Watcher"},
   {"Hunter", "Hunter"},
   {"Hunter", "Hunter"},
   {"Woodsman", "Woodswoman"},
   {"Woodsman", "Woodswoman"},
   {"Guide", "Guide"},
   {"Guide", "Guide"},
   {"Pathfinder", "Pathfinder"},
   {"Pathfinder", "Pathfinder"},
   {"Stalker", "Stalker"},
   {"Stalker", "Stalker"},
   {"Predator", "Predator"},
   {"Predator", "Predator"},
   {"Deerhunter", "Deerhunter"},
   {"Deerhunter", "Deerhunter"},
   {"Elkhunter", "Elkhunter"},
   {"Elkhunter", "Elkhunter"},
   {"Boarhunter", "Boarhunter"},
   {"Boarhunter", "Boarhunter"},
   {"Bearhunter", "Bearhunter"},
   {"Bearhunter", "Bearhunter"},
   {"Falconer", "Falconer"},
   {"Falconer", "Falconer"},
   {"Hawker", "Hawker"},
   {"Hawker", "Hawker"},
   {"Manhunter", "Manhunter"},
   {"Manhunter", "Manhunter"},
   {"Gianthunter", "Gianthunter"},
   {"Gianthunter", "Gianthunter"},
   {"Adept of the Hunt", "Adept of the Hunt"},
   {"Adept of the Hunt", "Adept of the Hunt"},
   {"Lord of the Hunt", "Lady of the Hunt"},
   {"Lord of the Hunt", "Lady of the Hunt"},
   {"Master of the Hunt", "Mistress of the Hunt"},
   {"Master of the Hunt", "Mistress of the Hunt"},
   {"Fox", "Fox"},
   {"Coyote", "Coyote"},
   {"Lynx", "Lynx"},
   {"Wolf", "Wolf"},
   {"Panther", "Panther"},
   {"Cougar", "Cougar"},
   {"Jaguar", "Jaguar"},
   {"Tiger", "Tiger"},
   {"Lion", "Lion"},
   {"Bear", "Bear"},
   {"Beastmaster", "Beastmaster"},
   {"Beastmaster", "Beastmaster"},
   {"Overlord of Beasts", "Overlord of Beasts"},
   {"Overlord of Beasts", "Overlord of Beasts"},
   {"Dragonhunter", "Dragonhunter"},
   {"Dragonhunter", "Dragonhunter"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Master Ranger", "Master Ranger"},
   {"Ranger Hero", "Ranger Heroine"},
   {"Squire of the Hunt", "Squire of the Hunt"},
   {"Knight of the Hunt", "Dame of the Hunt"},
   {"Demigod of Beasts", "Demigoddess of Beasts"},
   {"Immortal Hunter", "Immortal Huntress"},
   {"God of Beasts", "Goddess of Beasts"},
   {"Deity of Beasts", "Deity of Beasts"},
   {"Supremity of Beasts", "Supremity of Beasts"},
   {"Creator", "Creator"},
   {"Supreme Deity", "Supreme Deity"},
   },

/*	Druid	*/

  {
   {"Man", "Woman"},

   {"Apprentice of Nature", "Apprentice of Nature"},
   {"Student of Nature", "Student of Nature"},
   {"Student of Nature", "Student of Nature"},
   {"Scholar of Nature", "Scholar of Nature"},
   {"Scholar of Nature", "Scholar of Nature"},
   {"Neophyte", "Neophyte"},
   {"Neophyte", "Neophyte"},
   {"Naturalist", "Naturalist"},
   {"Naturalist", "Naturalist"},
   {"Forester", "Forestress"},
   {"Forester", "Forestress"},
   {"Student of Earth", "Student of Earth"},
   {"Student of Earth", "Student of Earth"},
   {"Student of Air", "Student of Air"},
   {"Student of Air", "Student of Air"},
   {"Student of Water", "Student of Water"},
   {"Student of Water", "Student of Water"},
   {"Student of Fire", "Student of Fire"},
   {"Student of Fire", "Student of Fire"},
   {"Student of Life", "Student of Life"},
   {"Student of Life", "Student of Life"},
   {"Student of The Elements", "Student of The Elements"},
   {"Student of The Elements", "Student of The Elements"},
   {"Herbalist", "Herbalist"},
   {"Herbalist", "Herbalist"},
   {"Philosopher", "Philosopher"},
   {"Philosopher", "Philosopher"},
   {"Sage", "Sage"},
   {"Sage", "Sage"},
   {"Prophet", "Prophetess"},
   {"Prophet", "Prophetess"},
   {"Adept of Earth", "Adept of Earth"},
   {"Adept of Earth", "Adept of Earth"},
   {"Adept of Air", "Adept of Air"},
   {"Adept of Air", "Adept of Air"},
   {"Adept of Water", "Adept of Water"},
   {"Adept of Water", "Adept of Water"},
   {"Adept of Fire", "Adept of Fire"},
   {"Adept of Fire", "Adept of Fire"},
   {"Adept of Life", "Adept of Life"},
   {"Adept of Life", "Adept of Life"},
   {"Adept of The Elements", "Adept of The Elements"},
   {"Adept of The Elements", "Adept of The Elements"},
   {"Druid of Earth", "Druidess of Earth"},
   {"Druid of Earth", "Druidess of Earth"},
   {"Druid of Air", "Druidess of Air"},
   {"Druid of Air", "Druidess of Air"},
   {"Druid of Water", "Druidess of Water"},
   {"Druid of Water", "Druidess of Water"},
   {"Druid of Fire", "Druidess of Fire"},
   {"Druid of Fire", "Druidess of Fire"},
   {"Druid of Life", "Druidess of Life"},
   {"Druid of Life", "Druidess of Life"},
   {"Druid of The Elements", "Druidess of The Elements"},
   {"Druid of The Elements", "Druidess of The Elements"},
   {"Sage of Earth", "Sage of Earth"},
   {"Sage of Earth", "Sage of Earth"},
   {"Sage of Air", "Sage of Air"},
   {"Sage of Air", "Sage of Air"},
   {"Sage of Water", "Sage of Water"},
   {"Sage of Water", "Sage of Water"},
   {"Sage of Fire", "Sage of Fire"},
   {"Sage of Fire", "Sage of Fire"},
   {"Sage of Life", "Sage of Life"},
   {"Sage of Life", "Sage of Life"},
   {"Sage of The Elements", "Sage of The Elements"},
   {"Sage of The Elements", "Sage of The Elements"},
   {"Master of Earth", "Mistress of Earth"},
   {"Master of Earth", "Mistress of Earth"},
   {"Master of Air", "Mistress of Air"},
   {"Master of Air", "Mistress of Air"},
   {"Master of Water", "Mistress of Water"},
   {"Master of Water", "Mistress of Water"},
   {"Master of Fire", "Mistress of Fire"},
   {"Master of Fire", "Mistress of Fire"},
   {"Master of Life", "Mistress of Life"},
   {"Master of Life", "Mistress of Life"},
   {"Master of The Elements", "Mistress of The Elements"},
   {"Master of The Elements", "Mistress of The Elements"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Master Druid", "Master Druid"},
   {"Druid Hero", "Druid Heroine"},
   {"Squire of The Elements", "Squire of The Elements"},
   {"Knight of The Elements", "Dame of The Elements"},
   {"Demigod of Nature", "Demigoddess of Nature"},
   {"Immortal Sage", "Immortal Sage"},
   {"God of The Elements", "Goddess of The Elements"},
   {"Deity of The Elements", "Deity of The Elements"},
   {"Supremity of The Elements", "Supremity of The Elements"},
   {"Creator", "Creator"},
   {"Supreme Diety", "Supreme Diety"},
   },

/*	Vampire	*/

  {
   {"Man", "Woman"},

   {"Blood Student", "Blood Student"},
   {"Scholar of Blood", "Scholar of Blood"},
   {"Scholar of Blood", "Scholar of Blood"},
   {"Student of the Night", "Student of the Night"},
   {"Student of the Night", "Student of the Night"},
   {"Student of Death", "Student of Death"},
   {"Student of Death", "Student of Death"},
   {"Lesser Imp", "Lesser Imp"},
   {"Greater Imp", "Greater Imp"},
   {"Illusionist", "Illusionist"},
   {"Illusionist", "Illusionist"},
   {"Seducer", "Seductress"},
   {"Seducer", "Seductress"},
   {"Stalker", "Stalker"},
   {"Stalker", "Stalker"},
   {"Stalker of Blood", "Stalker of Blood"},
   {"Stalker of Blood", "Stalker of Blood"},
   {"Stalker of Night", "Stalker of Night"},
   {"Stalker of Night", "Stalker of Night"},
   {"Stalker of Death", "Stalker of Death"},
   {"Stalker of Death", "Stalker of Death"},
   {"Shadow", "Shadow"},
   {"Shadow", "Shadow"},
   {"Shadow of Blood", "Shadow of Blood"},
   {"Shadow of Blood", "Shadow of Blood"},
   {"Shadow of Night", "Shadow of Night"},
   {"Shadow of Night", "Shadow of Night"},
   {"Shadow of Death", "Shadow of Death"},
   {"Shadow of Death", "Shadow of Death"},
   {"Killer", "Killer"},
   {"Killer", "Killer"},
   {"Murderer", "Murderer"},
   {"Murderer", "Murderer"},
   {"Incubus", "Succubus"},
   {"Incubus", "Succubus"},
   {"Nightstalker", "Nightstalker"},
   {"Nightstalker", "Nightstalker"},
   {"Revenant", "Revenant"},
   {"Revenant", "Revenant"},
   {"Lesser Vrolok", "Lesser Vrolok"},
   {"Vrolok", "Vrolok"},
   {"Greater Vrolok", "Greater Vrolok"},
   {"Demon Servant", "Demon Servant"},
   {"Demon Servant", "Demon Servant"},
   {"Adept of Blood", "Adept of Blood"},
   {"Adept of Blood", "Adept of Blood"},
   {"Adept of Night", "Adept of Night"},
   {"Adept of Night", "Adept of Night"},
   {"Adept of Death", "Adept of Death"},
   {"Adept of Death", "Adept of Death"},
   {"Demon Seeker", "Demon Seeker"},
   {"Demon Seeker", "Demon Seeker"},
   {"Lord of Blood", "Lady of Blood"},
   {"Lord of Blood", "Lady of Blood"},
   {"Lord of Night", "Lady of Night"},
   {"Lord of Night", "Lady of Night"},
   {"Lord of Death", "Lady of Death"},
   {"Lord of Death", "Lady of Death"},
   {"Demon Knight", "Demon Dame"},
   {"Demon Knight", "Demon Dame"},
   {"Master of Blood", "Mistress of Blood"},
   {"Master of Blood", "Mistress of Blood"},
   {"Master of Night", "Mistress of Night"},
   {"Master of Night", "Mistress of Night"},
   {"Master of Death", "Mistress of Death"},
   {"Master of Death", "Mistress of Death"},
   {"Lord of Demons", "Lady of Demons"},
   {"Lord of Demons", "Lady of Demons"},
   {"Baron of Demons", "Baroness of Demons"},
   {"Baron of Demons", "Baroness of Demons"},
   {"Master of Demons", "Mistress of Demons"},
   {"Master of Demons", "Mistress of Demons"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Master Vampire", "Master Vampire"},
   {"Vampire Hero", "Vampire Heroine"},
   {"Squire of Blood", "Squire of Blood"},
   {"Knight of Blood", "Dame of Blood"},
   {"Demigod of the Night", "Demigoddess of the Night"},
   {"Immortal Undead", "Immortal Undead"},
   {"God of Death", "Goddess of Death"},
   {"Deity of Death", "Deity of Death"},
   {"Supremity of Death", "Supremity of Death"},
   {"Creator", "Creator"},
   {"Supreme Diety", "Supreme Deity"},
   },

/*	Wizard	*/

  {
   {"Man", "Woman"},

   {"Novice of Magic", "Novice of Magic"},
   {"Apprentice of Magic", "Apprentice of Magic"},
   {"Spell Novice", "Spell Novice"},
   {"Spell Student", "Spell Student"},
   {"Scholar of Magic", "Scholar of Magic"},
   {"Scholar of Wizardry", "Scholar of Wizardry"},
   {"Delver in Scrolls", "Delveress in Scrolls"},
   {"Delver in Spells", "Delveress in Spells"},
   {"Medium of Magic", "Medium of Magic"},
   {"Medium of Wizardry", "Medium of Wizardry"},
   {"Scribe of Magic", "Scribess of Magic"},
   {"Scribe of Wizardry", "Scribess of Wizardry"},
   {"Minor Seer", "Minor Seeress"},
   {"Seer", "Seeress"},
   {"Minor Sage", "Minor Sage"},
   {"Sage", "Sage"},
   {"Minor Illusionist", "Minor Illusionist"},
   {"Illusionist", "Illusionist"},
   {"Minor Abjurer", "Minor Abjuress"},
   {"Abjurer", "Abjuress"},
   {"Minor Invoker", "Minor Invoker"},
   {"Invoker", "Invoker"},
   {"Minor Enchanter", "Minor Enchantress"},
   {"Enchanter", "Enchantress"},
   {"Minor Conjurer", "Minor Conjuress"},
   {"Conjurer", "Conjuress"},
   {"Minor Magician", "Minor Witch"},
   {"Magician", "Witch"},
   {"Minor Creator", "Minor Creator"},
   {"Creator", "Creator"},
   {"Minor Savant", "Minor Savant"},
   {"Savant", "Savant"},
   {"Minor Magus", "Minor Craftess"},
   {"Magus", "Craftess"},
   {"Minor Wizard", "Minor Wizard"},
   {"Wizard", "Wizard"},
   {"Minor Warlock", "Minor War Witch"},
   {"Warlock", "War Witch"},
   {"Minor Sorcerer", "Minor Sorceress"},
   {"Sorcerer", "Sorceress"},
   {"Elder Sorcerer", "Elder Sorceress"},
   {"Elder Sorcerer", "Elder Sorceress"},
   {"Grand Sorcerer", "Grand Sorceress"},
   {"Grand Sorcerer", "Grand Sorceress"},
   {"Great Sorcerer", "Great Sorceress"},
   {"Great Sorcerer", "Great Sorceress"},
   {"Golem Maker", "Golem Maker"},
   {"Golem Maker", "Golem Maker"},
   {"Greater Golem Maker", "Greater Golem Maker"},
   {"Greater Golem Maker", "Greater Golem Maker"},
   {"Maker of Stones", "Maker of Stones",},
   {"Maker of Stones", "Maker of Stones",},
   {"Maker of Potions", "Maker of Potions",},
   {"Maker of Potions", "Maker of Potions",},
   {"Maker of Scrolls", "Maker of Scrolls",},
   {"Maker of Scrolls", "Maker of Scrolls",},
   {"Maker of Wands", "Maker of Wands",},
   {"Maker of Wands", "Maker of Wands",},
   {"Maker of Staves", "Maker of Staves",},
   {"Maker of Staves", "Maker of Staves",},
   {"Demon Summoner", "Demon Summoner"},
   {"Demon Summoner", "Demon Summoner"},
   {"Greater Demon Summoner", "Greater Demon Summoner"},
   {"Greater Demon Summoner", "Greater Demon Summoner"},
   {"Dragon Charmer", "Dragon Charmer"},
   {"Dragon Charmer", "Dragon Charmer"},
   {"Greater Dragon Charmer", "Greater Dragon Charmer"},
   {"Greater Dragon Charmer", "Greater Dragon Charmer"},
   {"Master of all Magic", "Master of all Magic"},
   {"Master of all Magic", "Master of all Magic"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Master Wizard", "Master Wizard"},
   {"Wizard Hero", "Wizard Heroine"},
   {"Squire of Magic", "Squire of Magic"},
   {"Knight of Magic", "Dame of Magic"},
   {"Demigod of Magic", "Demigoddess of Magic"},
   {"Immortal of Magic", "Immortal of Magic"},
   {"God of Magic", "Goddess of Magic"},
   {"Deity of Magic", "Deity of Magic"},
   {"Supremity of Magic", "Supremity of Magic"},
   {"Creator", "Creator"},
   {"Supreme Deity", "Supreme Deity"}
   },

/*	Priest	*/

  {
   {"Man", "Woman"},

   {"Believer", "Believer"},
   {"Believer", "Believer"},
   {"Attendant", "Attendant"},
   {"Attendant", "Attendant"},
   {"Acolyte", "Acolyte"},
   {"Acolyte", "Acolyte"},
   {"Novice", "Novice"},
   {"Novice", "Novice"},
   {"Missionary", "Missionary"},
   {"Missionary", "Missionary"},
   {"Adept", "Adept"},
   {"Adept", "Adept"},
   {"Deacon", "Deaconess"},
   {"Deacon", "Deaconess"},
   {"Vicar", "Vicaress"},
   {"Vicar", "Vicaress"},
   {"Priest", "Priestess"},
   {"Priest", "Priestess"},
   {"Minister", "Lady Minister"},
   {"Minister", "Lady Minister"},
   {"Canon", "Canon"},
   {"Canon", "Canon"},
   {"Levite", "Levitess"},
   {"Levite", "Levitess"},
   {"Curate", "Curess"},
   {"Curate", "Curess"},
   {"Monk", "Nun"},
   {"Monk", "Nun"},
   {"Healer", "Healess"},
   {"Healer", "Healess"},
   {"Chaplain", "Chaplain"},
   {"Chaplain", "Chaplain"},
   {"Expositor", "Expositress"},
   {"Expositor", "Expositress"},
   {"Bishop", "Bishop"},
   {"Bishop", "Bishop"},
   {"Arch Bishop", "Arch Lady of the Church"},
   {"Arch Bishop", "Arch Lady of the Church"},
   {"Patriarch", "Matriarch"},
   {"Patriarch", "Matriarch"},
   {"Elder Patriarch", "Elder Matriarch"},
   {"Elder Patriarch", "Elder Matriarch"},
   {"Grand Patriarch", "Grand Matriarch"},
   {"Grand Patriarch", "Grand Matriarch"},
   {"Great Patriarch", "Great Matriarch"},
   {"Great Patriarch", "Great Matriarch"},
   {"Demon Killer", "Demon Killer"},
   {"Demon Killer", "Demon Killer"},
   {"Greater Demon Killer", "Greater Demon Killer"},
   {"Greater Demon Killer", "Greater Demon Killer"},
   {"Cardinal of the Sea", "Cardinal of the Sea"},
   {"Cardinal of the Sea", "Cardinal of the Sea"},
   {"Cardinal of the Earth", "Cardinal of the Earth"},
   {"Cardinal of the Earth", "Cardinal of the Earth"},
   {"Cardinal of the Air", "Cardinal of the Air"},
   {"Cardinal of the Air", "Cardinal of the Air"},
   {"Cardinal of the Ether", "Cardinal of the Ether"},
   {"Cardinal of the Ether", "Cardinal of the Ether"},
   {"Cardinal of the Heavens", "Cardinal of the Heavens"},
   {"Cardinal of the Heavens", "Cardinal of the Heavens"},
   {"Avatar of an Immortal", "Avatar of an Immortal"},
   {"Avatar of an Immortal", "Avatar of an Immortal"},
   {"Avatar of a Deity", "Avatar of a Deity"},
   {"Avatar of a Deity", "Avatar of a Deity"},
   {"Avatar of a Supremity", "Avatar of a Supremity"},
   {"Avatar of a Supremity", "Avatar of a Supremity"},
   {"Avatar of an Implementor", "Avatar of an Implementor"},
   {"Avatar of an Implementor", "Avatar of an Implementor"},
   {"Master of all Divinity", "Mistress of all Divinity"},
   {"Master of all Divinity", "Mistress of all Divinity"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Master Priest", "Master Priestess"},
   {"Divine Hero", "Divine Heroine"},
   {"Divine Squire", "Divine Squire"},
   {"Divine Knight", "Divine Dame"},
   {"Demigod", "Demigoddess",},
   {"Immortal", "Immortal"},
   {"God", "Goddess"},
   {"Deity", "Deity"},
   {"Supreme Master", "Supreme Mistress"},
   {"Creator", "Creator"},
   {"Supreme Deity", "Supreme Deity"}
   },

/*	Mercenary	*/

  {
   {"Man", "Woman"},

   {"Pilferer", "Pilferess"},
   {"Pilferer", "Pilferess"},
   {"Footpad", "Footpad"},
   {"Footpad", "Footpad"},
   {"Filcher", "Filcheress"},
   {"Filcher", "Filcheress"},
   {"Pick-Pocket", "Pick-Pocket"},
   {"Pick-Pocket", "Pick-Pocket"},
   {"Sneak", "Sneak"},
   {"Sneak", "Sneak"},
   {"Pincher", "Pincheress"},
   {"Pincher", "Pincheress"},
   {"Cut-Purse", "Cut-Purse"},
   {"Cut-Purse", "Cut-Purse"},
   {"Snatcher", "Snatcheress"},
   {"Snatcher", "Snatcheress"},
   {"Sharper", "Sharpress"},
   {"Sharper", "Sharpress"},
   {"Rogue", "Rogue"},
   {"Rogue", "Rogue"},
   {"Robber", "Robber"},
   {"Robber", "Robber"},
   {"Magsman", "Magswoman"},
   {"Magsman", "Magswoman"},
   {"Highwayman", "Highwaywoman"},
   {"Highwayman", "Highwaywoman"},
   {"Burglar", "Burglaress"},
   {"Burglar", "Burglaress"},
   {"Thief", "Thief"},
   {"Thief", "Thief"},
   {"Knifer", "Knifer"},
   {"Knifer", "Knifer"},
   {"Quick-Blade", "Quick-Blade"},
   {"Quick-Blade", "Quick-Blade"},
   {"Killer", "Murderess"},
   {"Killer", "Murderess"},
   {"Brigand", "Brigand"},
   {"Brigand", "Brigand"},
   {"Cut-Throat", "Cut-Throat"},
   {"Cut-Throat", "Cut-Throat"},
   {"Spy", "Spy"},
   {"Spy", "Spy"},
   {"Grand Spy", "Grand Spy"},
   {"Grand Spy", "Grand Spy"},
   {"Master Spy", "Master Spy"},
   {"Master Spy", "Master Spy"},
   {"Assassin", "Assassin"},
   {"Assassin", "Assassin"},
   {"Greater Assassin", "Greater Assassin"},
   {"Greater Assassin", "Greater Assassin"},
   {"Master of Vision", "Mistress of Vision"},
   {"Master of Vision", "Mistress of Vision"},
   {"Master of Hearing", "Mistress of Hearing"},
   {"Master of Hearing", "Mistress of Hearing"},
   {"Master of Smell", "Mistress of Smell"},
   {"Master of Smell", "Mistress of Smell"},
   {"Master of Taste", "Mistress of Taste"},
   {"Master of Taste", "Mistress of Taste"},
   {"Master of Touch", "Mistress of Touch"},
   {"Master of Touch", "Mistress of Touch"},
   {"Crime Lord", "Crime Mistress"},
   {"Crime Lord", "Crime Mistress"},
   {"Infamous Crime Lord", "Infamous Crime Mistress"},
   {"Infamous Crime Lord", "Infamous Crime Mistress"},
   {"Greater Crime Lord", "Greater Crime Mistress"},
   {"Greater Crime Lord", "Greater Crime Mistress"},
   {"Master Crime Lord", "Master Crime Mistress"},
   {"Master Crime Lord", "Master Crime Mistress"},
   {"Godfather", "Godmother"},
   {"Godfather", "Godmother"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Master Mercenary", "Master Mercenary"},
   {"Assassin Hero", "Assassin Heroine"},
   {"Squire of Death", "Squire of Death",},
   {"Knight of Death", "Dame of Death"},
   {"Demigod of Assassins", "Demigoddess of Assassins"},
   {"Immortal Assasin", "Immortal Assassin"},
   {"God of Assassins", "God of Assassins",},
   {"Deity of Assassins", "Deity of Assassins"},
   {"Supreme Master", "Supreme Mistress"},
   {"Creator", "Creator"},
   {"Supreme Deity", "Supreme Deity"}
   },

/*	Gladiator	*/

  {
   {"Man", "Woman"},

   {"Swordpupil", "Swordpupil"},
   {"Swordpupil", "Swordpupil"},
   {"Recruit", "Recruit"},
   {"Recruit", "Recruit"},
   {"Sentry", "Sentress"},
   {"Sentry", "Sentress"},
   {"Fighter", "Fighter"},
   {"Fighter", "Fighter"},
   {"Soldier", "Soldier"},
   {"Soldier", "Soldier"},
   {"Warrior", "Warrior"},
   {"Warrior", "Warrior"},
   {"Veteran", "Veteran"},
   {"Veteran", "Veteran"},
   {"Swordsman", "Swordswoman"},
   {"Swordsman", "Swordswoman"},
   {"Fencer", "Fenceress"},
   {"Fencer", "Fenceress"},
   {"Combatant", "Combatess"},
   {"Combatant", "Combatess"},
   {"Hero", "Heroine"},
   {"Hero", "Heroine"},
   {"Myrmidon", "Myrmidon"},
   {"Myrmidon", "Myrmidon"},
   {"Swashbuckler", "Swashbuckleress"},
   {"Swashbuckler", "Swashbuckleress"},
   {"Mercenary", "Mercenaress"},
   {"Mercenary", "Mercenaress"},
   {"Swordmaster", "Swordmistress"},
   {"Swordmaster", "Swordmistress"},
   {"Lieutenant", "Lieutenant"},
   {"Lieutenant", "Lieutenant"},
   {"Champion", "Lady Champion"},
   {"Champion", "Lady Champion"},
   {"Dragoon", "Lady Dragoon"},
   {"Dragoon", "Lady Dragoon"},
   {"Cavalier", "Lady Cavalier"},
   {"Cavalier", "Lady Cavalier"},
   {"Knight", "Lady Knight"},
   {"Knight", "Lady Knight"},
   {"Grand Knight", "Grand Knight"},
   {"Grand Knight", "Grand Knight"},
   {"Master Knight", "Master Knight"},
   {"Master Knight", "Master Knight"},
   {"Strider", "Strider"},
   {"Strider", "Strider"},
   {"Grand Strider", "Grand Strider"},
   {"Grand Strider", "Grand Strider"},
   {"Demon Slayer", "Demon Slayer"},
   {"Demon Slayer", "Demon Slayer"},
   {"Greater Demon Slayer", "Greater Demon Slayer"},
   {"Greater Demon Slayer", "Greater Demon Slayer"},
   {"Dragon Slayer", "Dragon Slayer"},
   {"Dragon Slayer", "Dragon Slayer"},
   {"Greater Dragon Slayer", "Greater Dragon Slayer"},
   {"Greater Dragon Slayer", "Greater Dragon Slayer"},
   {"Underlord", "Underlord"},
   {"Underlord", "Underlord"},
   {"Overlord", "Overlord"},
   {"Overlord", "Overlord"},
   {"Baron of Thunder", "Baroness of Thunder"},
   {"Baron of Thunder", "Baroness of Thunder"},
   {"Baron of Storms", "Baroness of Storms"},
   {"Baron of Storms", "Baroness of Storms"},
   {"Baron of Tornadoes", "Baroness of Tornadoes"},
   {"Baron of Tornadoes", "Baroness of Tornadoes"},
   {"Baron of Hurricanes", "Baroness of Hurricanes"},
   {"Baron of Hurricanes", "Baroness of Hurricanes"},
   {"Baron of Meteors", "Baroness of Meteors"},
   {"Baron of Meteors", "Baroness of Meteors"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Master Gladiator", "Master Gladiator"},
   {"Centurian Hero", "Centurian Heroine"},
   {"Squire of War", "Squire of War"},
   {"Knight of War", "Dame of War"},
   {"Demigod of War", "Demigoddess of War"},
   {"Immortal Warlord", "Immortal Warlord"},
   {"God of War", "God of War"},
   {"Deity of War", "Deity of War"},
   {"Supreme Master of War", "Supreme Mistress of War"},
   {"Creator", "Creator"},
   {"Supreme Deity", "Supreme Deity"}
   },

/*	Strider	*/

  {
   {"Man", "Woman"},

   {"Apprentice of the Hunt", "Apprentice of the Hunt"},
   {"Student of the Hunt", "Student of the Hunt"},
   {"Student of the Hunt", "Student of the Hunt"},
   {"Runner", "Runner"},
   {"Runner", "Runner"},
   {"Strider", "Strider"},
   {"Strider", "Strider"},
   {"Scout", "Scout"},
   {"Scout", "Scout"},
   {"Master Scout", "Master Scout"},
   {"Master Scout", "Master Scout"},
   {"Explorer", "Explorer"},
   {"Explorer", "Explorer"},
   {"Tracker", "Tracker"},
   {"Tracker", "Tracker"},
   {"Survivalist", "Survivalist"},
   {"Survivalist", "Survivalist"},
   {"Watcher", "Watcher"},
   {"Watcher", "Watcher"},
   {"Hunter", "Hunter"},
   {"Hunter", "Hunter"},
   {"Woodsman", "Woodswoman"},
   {"Woodsman", "Woodswoman"},
   {"Guide", "Guide"},
   {"Guide", "Guide"},
   {"Pathfinder", "Pathfinder"},
   {"Pathfinder", "Pathfinder"},
   {"Stalker", "Stalker"},
   {"Stalker", "Stalker"},
   {"Predator", "Predator"},
   {"Predator", "Predator"},
   {"Deerhunter", "Deerhunter"},
   {"Deerhunter", "Deerhunter"},
   {"Elkhunter", "Elkhunter"},
   {"Elkhunter", "Elkhunter"},
   {"Boarhunter", "Boarhunter"},
   {"Boarhunter", "Boarhunter"},
   {"Bearhunter", "Bearhunter"},
   {"Bearhunter", "Bearhunter"},
   {"Falconer", "Falconer"},
   {"Falconer", "Falconer"},
   {"Hawker", "Hawker"},
   {"Hawker", "Hawker"},
   {"Manhunter", "Manhunter"},
   {"Manhunter", "Manhunter"},
   {"Gianthunter", "Gianthunter"},
   {"Gianthunter", "Gianthunter"},
   {"Adept of the Hunt", "Adept of the Hunt"},
   {"Adept of the Hunt", "Adept of the Hunt"},
   {"Lord of the Hunt", "Lady of the Hunt"},
   {"Lord of the Hunt", "Lady of the Hunt"},
   {"Master of the Hunt", "Mistress of the Hunt"},
   {"Master of the Hunt", "Mistress of the Hunt"},
   {"Fox", "Fox"},
   {"Coyote", "Coyote"},
   {"Lynx", "Lynx"},
   {"Wolf", "Wolf"},
   {"Panther", "Panther"},
   {"Cougar", "Cougar"},
   {"Jaguar", "Jaguar"},
   {"Tiger", "Tiger"},
   {"Lion", "Lion"},
   {"Bear", "Bear"},
   {"Beastmaster", "Beastmaster"},
   {"Beastmaster", "Beastmaster"},
   {"Overlord of Beasts", "Overlord of Beasts"},
   {"Overlord of Beasts", "Overlord of Beasts"},
   {"Dragonhunter", "Dragonhunter"},
   {"Dragonhunter", "Dragonhunter"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Master Strider", "Master Strider"},
   {"Strider Hero", "Strider Heroine"},
   {"Squire of the Hunt", "Squire of the Hunt"},
   {"Knight of the Hunt", "Dame of the Hunt"},
   {"Demigod of Beasts", "Demigoddess of Beasts"},
   {"Immortal Hunter", "Immortal Huntress"},
   {"God of Beasts", "Goddess of Beasts"},
   {"Deity of Beasts", "Deity of Beasts"},
   {"Supremity of Beasts", "Supremity of Beasts"},
   {"Creator", "Creator"},
   {"Supreme Deity", "Supreme Deity"},
   },

/*	Sage	*/

  {
   {"Man", "Woman"},

   {"Apprentice of Nature", "Apprentice of Nature"},
   {"Student of Nature", "Student of Nature"},
   {"Student of Nature", "Student of Nature"},
   {"Scholar of Nature", "Scholar of Nature"},
   {"Scholar of Nature", "Scholar of Nature"},
   {"Neophyte", "Neophyte"},
   {"Neophyte", "Neophyte"},
   {"Naturalist", "Naturalist"},
   {"Naturalist", "Naturalist"},
   {"Forester", "Forestress"},
   {"Forester", "Forestress"},
   {"Student of Earth", "Student of Earth"},
   {"Student of Earth", "Student of Earth"},
   {"Student of Air", "Student of Air"},
   {"Student of Air", "Student of Air"},
   {"Student of Water", "Student of Water"},
   {"Student of Water", "Student of Water"},
   {"Student of Fire", "Student of Fire"},
   {"Student of Fire", "Student of Fire"},
   {"Student of Life", "Student of Life"},
   {"Student of Life", "Student of Life"},
   {"Student of The Elements", "Student of The Elements"},
   {"Student of The Elements", "Student of The Elements"},
   {"Herbalist", "Herbalist"},
   {"Herbalist", "Herbalist"},
   {"Philosopher", "Philosopher"},
   {"Philosopher", "Philosopher"},
   {"Sage", "Sage"},
   {"Sage", "Sage"},
   {"Prophet", "Prophetess"},
   {"Prophet", "Prophetess"},
   {"Adept of Earth", "Adept of Earth"},
   {"Adept of Earth", "Adept of Earth"},
   {"Adept of Air", "Adept of Air"},
   {"Adept of Air", "Adept of Air"},
   {"Adept of Water", "Adept of Water"},
   {"Adept of Water", "Adept of Water"},
   {"Adept of Fire", "Adept of Fire"},
   {"Adept of Fire", "Adept of Fire"},
   {"Adept of Life", "Adept of Life"},
   {"Adept of Life", "Adept of Life"},
   {"Adept of The Elements", "Adept of The Elements"},
   {"Adept of The Elements", "Adept of The Elements"},
   {"Druid of Earth", "Druidess of Earth"},
   {"Druid of Earth", "Druidess of Earth"},
   {"Druid of Air", "Druidess of Air"},
   {"Druid of Air", "Druidess of Air"},
   {"Druid of Water", "Druidess of Water"},
   {"Druid of Water", "Druidess of Water"},
   {"Druid of Fire", "Druidess of Fire"},
   {"Druid of Fire", "Druidess of Fire"},
   {"Druid of Life", "Druidess of Life"},
   {"Druid of Life", "Druidess of Life"},
   {"Druid of The Elements", "Druidess of The Elements"},
   {"Druid of The Elements", "Druidess of The Elements"},
   {"Sage of Earth", "Sage of Earth"},
   {"Sage of Earth", "Sage of Earth"},
   {"Sage of Air", "Sage of Air"},
   {"Sage of Air", "Sage of Air"},
   {"Sage of Water", "Sage of Water"},
   {"Sage of Water", "Sage of Water"},
   {"Sage of Fire", "Sage of Fire"},
   {"Sage of Fire", "Sage of Fire"},
   {"Sage of Life", "Sage of Life"},
   {"Sage of Life", "Sage of Life"},
   {"Sage of The Elements", "Sage of The Elements"},
   {"Sage of The Elements", "Sage of The Elements"},
   {"Master of Earth", "Mistress of Earth"},
   {"Master of Earth", "Mistress of Earth"},
   {"Master of Air", "Mistress of Air"},
   {"Master of Air", "Mistress of Air"},
   {"Master of Water", "Mistress of Water"},
   {"Master of Water", "Mistress of Water"},
   {"Master of Fire", "Mistress of Fire"},
   {"Master of Fire", "Mistress of Fire"},
   {"Master of Life", "Mistress of Life"},
   {"Master of Life", "Mistress of Life"},
   {"Master of The Elements", "Mistress of The Elements"},
   {"Master of The Elements", "Mistress of The Elements"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Master Sage", "Master Sage"},
   {"Sage Hero", "Sage Heroine"},
   {"Squire of The Elements", "Squire of The Elements"},
   {"Knight of The Elements", "Dame of The Elements"},
   {"Demigod of Nature", "Demigoddess of Nature"},
   {"Immortal Sage", "Immortal Sage"},
   {"God of The Elements", "Goddess of The Elements"},
   {"Deity of The Elements", "Deity of The Elements"},
   {"Supremity of The Elements", "Supremity of The Elements"},
   {"Creator", "Creator"},
   {"Supreme Diety", "Supreme Diety"},
   },

/*	Lich	*/
  {
   {"Man", "Woman"},

   {"Blood Student", "Blood Student"},
   {"Scholar of Blood", "Scholar of Blood"},
   {"Scholar of Blood", "Scholar of Blood"},
   {"Student of the Night", "Student of the Night"},
   {"Student of the Night", "Student of the Night"},
   {"Student of Death", "Student of Death"},
   {"Student of Death", "Student of Death"},
   {"Lesser Imp", "Lesser Imp"},
   {"Greater Imp", "Greater Imp"},
   {"Illusionist", "Illusionist"},
   {"Illusionist", "Illusionist"},
   {"Seducer", "Seductress"},
   {"Seducer", "Seductress"},
   {"Stalker", "Stalker"},
   {"Stalker", "Stalker"},
   {"Stalker of Blood", "Stalker of Blood"},
   {"Stalker of Blood", "Stalker of Blood"},
   {"Stalker of Night", "Stalker of Night"},
   {"Stalker of Night", "Stalker of Night"},
   {"Stalker of Death", "Stalker of Death"},
   {"Stalker of Death", "Stalker of Death"},
   {"Shadow", "Shadow"},
   {"Shadow", "Shadow"},
   {"Shadow of Blood", "Shadow of Blood"},
   {"Shadow of Blood", "Shadow of Blood"},
   {"Shadow of Night", "Shadow of Night"},
   {"Shadow of Night", "Shadow of Night"},
   {"Shadow of Death", "Shadow of Death"},
   {"Shadow of Death", "Shadow of Death"},
   {"Killer", "Killer"},
   {"Killer", "Killer"},
   {"Murderer", "Murderer"},
   {"Murderer", "Murderer"},
   {"Incubus", "Succubus"},
   {"Incubus", "Succubus"},
   {"Nightstalker", "Nightstalker"},
   {"Nightstalker", "Nightstalker"},
   {"Revenant", "Revenant"},
   {"Revenant", "Revenant"},
   {"Lesser Vrolok", "Lesser Vrolok"},
   {"Vrolok", "Vrolok"},
   {"Greater Vrolok", "Greater Vrolok"},
   {"Demon Servant", "Demon Servant"},
   {"Demon Servant", "Demon Servant"},
   {"Adept of Blood", "Adept of Blood"},
   {"Adept of Blood", "Adept of Blood"},
   {"Adept of Night", "Adept of Night"},
   {"Adept of Night", "Adept of Night"},
   {"Adept of Death", "Adept of Death"},
   {"Adept of Death", "Adept of Death"},
   {"Demon Seeker", "Demon Seeker"},
   {"Demon Seeker", "Demon Seeker"},
   {"Lord of Blood", "Lady of Blood"},
   {"Lord of Blood", "Lady of Blood"},
   {"Lord of Night", "Lady of Night"},
   {"Lord of Night", "Lady of Night"},
   {"Lord of Death", "Lady of Death"},
   {"Lord of Death", "Lady of Death"},
   {"Demon Knight", "Demon Dame"},
   {"Demon Knight", "Demon Dame"},
   {"Master of Blood", "Mistress of Blood"},
   {"Master of Blood", "Mistress of Blood"},
   {"Master of Night", "Mistress of Night"},
   {"Master of Night", "Mistress of Night"},
   {"Master of Death", "Mistress of Death"},
   {"Master of Death", "Mistress of Death"},
   {"Lord of Demons", "Lady of Demons"},
   {"Lord of Demons", "Lady of Demons"},
   {"Baron of Demons", "Baroness of Demons"},
   {"Baron of Demons", "Baroness of Demons"},
   {"Master of Demons", "Mistress of Demons"},
   {"Master of Demons", "Mistress of Demons"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Master Lich", "Master Lich"},
   {"Lich Hero", "Lich Heroine"},
   {"Squire of Blood", "Squire of Blood"},
   {"Knight of Blood", "Dame of Blood"},
   {"Demigod of the Night", "Demigoddess of the Night"},
   {"Immortal Undead", "Immortal Undead"},
   {"God of Death", "Goddess of Death"},
   {"Deity of Death", "Deity of Death"},
   {"Supremity of Death", "Supremity of Death"},
   {"Creator", "Creator"},
   {"Supreme Diety", "Supreme Deity"},
   }
};



/*
 * Attribute bonus tables.
 */
const struct str_app_type str_app[26] = {
  {-5, -4, 0, 0},		/* 0  */
  {-5, -4, 3, 1},		/* 1  */
  {-3, -2, 3, 2},
  {-3, -1, 10, 3},		/* 3  */
  {-2, -1, 25, 4},
  {-2, -1, 55, 5},		/* 5  */
  {-1, 0, 80, 6},
  {-1, 0, 90, 7},
  {0, 0, 100, 8},
  {0, 0, 100, 9},
  {0, 0, 115, 10},		/* 10  */
  {0, 0, 115, 11},
  {0, 0, 130, 12},
  {0, 0, 130, 13},		/* 13  */
  {0, 1, 140, 14},
  {1, 1, 150, 15},		/* 15  */
  {1, 2, 165, 16},
  {2, 3, 180, 22},
  {2, 3, 200, 25},		/* 18  */
  {3, 4, 225, 30},
  {3, 5, 250, 35},		/* 20  */
  {4, 6, 300, 40},
  {4, 6, 350, 45},
  {5, 7, 400, 50},
  {5, 8, 450, 55},
  {6, 9, 500, 60}		/* 25   */
};



const struct int_app_type int_app[26] = {
  {3},				/*  0 */
  {5},				/*  1 */
  {7},
  {8},				/*  3 */
  {9},
  {10},				/*  5 */
  {11},
  {12},
  {13},
  {15},
  {17},				/* 10 */
  {19},
  {22},
  {25},
  {28},
  {31},				/* 15 */
  {34},
  {37},
  {40},				/* 18 */
  {44},
  {49},				/* 20 */
  {55},
  {60},
  {70},
  {80},
  {85}				/* 25 */
};



const struct wis_app_type wis_app[26] = {
  {0},				/*  0 */
  {0},				/*  1 */
  {0},
  {0},				/*  3 */
  {0},
  {1},				/*  5 */
  {1},
  {1},
  {1},
  {1},
  {1},				/* 10 */
  {1},
  {1},
  {1},
  {1},
  {2},				/* 15 */
  {2},
  {2},
  {3},				/* 18 */
  {3},
  {3},				/* 20 */
  {3},
  {4},
  {4},
  {4},
  {5}				/* 25 */
};



const struct dex_app_type dex_app[26] = {
  {60},				/* 0 */
  {50},				/* 1 */
  {50},
  {40},
  {30},
  {20},				/* 5 */
  {10},
  {0},
  {0},
  {0},
  {0},				/* 10 */
  {0},
  {0},
  {0},
  {0},
  {-10},			/* 15 */
  {-15},
  {-20},
  {-30},
  {-40},
  {-50},			/* 20 */
  {-60},
  {-75},
  {-90},
  {-105},
  {-120}			/* 25 */
};


const struct con_app_type con_app[26] = {
  {-4, 20},			/*  0 */
  {-3, 25},			/*  1 */
  {-2, 30},
  {-2, 35},			/*  3 */
  {-1, 40},
  {-1, 45},			/*  5 */
  {-1, 50},
  {0, 55},
  {0, 60},
  {0, 65},
  {0, 70},			/* 10 */
  {0, 75},
  {0, 80},
  {0, 85},
  {0, 88},
  {1, 90},			/* 15 */
  {2, 95},
  {2, 97},
  {3, 99},			/* 18 */
  {3, 99},
  {4, 99},			/* 20 */
  {4, 99},
  {5, 99},
  {6, 99},
  {7, 99},
  {8, 99}			/* 25 */
};



/*
 * Liquid properties.
 * Used in world.obj.
 * Be sure MAX_LIQUID in merc.h matches
 * the number of entries below.
 */
const struct liq_type liq_table[] = {
/*    name			color	proof, full, thirst, food, ssize */
  {"water", "clear", {0, 1, 10, 0, 16}},
  {"beer", "amber", {12, 1, 8, 1, 12}},
  {"red wine", "burgundy", {30, 1, 8, 1, 5}},
  {"ale", "brown", {15, 1, 8, 1, 12}},
  {"dark ale", "dark", {16, 1, 8, 1, 12}},

  {"whisky", "golden", {120, 1, 5, 0, 2}},
  {"lemonade", "pink", {0, 1, 9, 2, 12}},
  {"firebreather", "boiling", {190, 0, 4, 0, 2}},
  {"local specialty", "clear", {151, 1, 3, 0, 2}},
  {"slime mold juice", "green", {0, 2, -8, 1, 2}},

  {"milk", "white", {0, 2, 9, 3, 12}},
  {"tea", "tan", {0, 1, 8, 0, 6}},
  {"coffee", "black", {0, 1, 8, 0, 6}},
  {"blood", "red", {0, 2, -1, 2, 6}},
  {"salt water", "clear", {0, 1, -2, 0, 1}},

  {"coke", "brown", {0, 2, 9, 2, 12}},
  {"root beer", "brown", {0, 2, 9, 2, 12}},
  {"elvish wine", "green", {35, 2, 8, 1, 5}},
  {"white wine", "golden", {28, 1, 8, 1, 5}},
  {"champagne", "golden", {32, 1, 8, 1, 5}},

  {"mead", "honey-colored", {34, 2, 8, 2, 12}},
  {"rose wine", "pink", {26, 1, 8, 1, 5}},
  {"benedictine wine", "burgundy", {40, 1, 8, 1, 5}},
  {"vodka", "clear", {130, 1, 5, 0, 2}},
  {"cranberry juice", "red", {0, 1, 9, 2, 12}},

  {"orange juice", "orange", {0, 2, 9, 3, 12}},
  {"absinthe", "green", {200, 1, 4, 0, 2}},
  {"brandy", "golden", {80, 1, 5, 0, 4}},
  {"aquavit", "clear", {140, 1, 5, 0, 2}},
  {"schnapps", "clear", {90, 1, 5, 0, 2}},

  {"icewine", "purple", {50, 2, 6, 1, 5}},
  {"amontillado", "burgundy", {35, 2, 8, 1, 5}},
  {"sherry", "red", {38, 2, 7, 1, 5}},
  {"framboise", "red", {50, 1, 7, 1, 5}},
  {"rum", "amber", {151, 1, 4, 0, 2}},

  {"cordial", "clear", {100, 1, 5, 0, 2}},
  {"dr pepper", "brown", {0, 2, 9, 2, 12}},
  {NULL, NULL, {0, 0, 0, 0, 0}}
};


